
platform: linux
image_resource:
  type: registry-image
  source: { repository: busybox }

inputs:
- name: bucc-aws-repo

outputs:
- name: deployment-stuff

run:
  path: sh
  args:
  - -exc
  - |
    cat <<EOF > deployment-stuff/manifest.yml
    applications:
      name: silly-app
      memory: 64M
    EOF
